#############################################################################################
### ONLY BUILDS MAP STYLES
#############################################################################################
steps:
    -   name: 'node:8'
        args: ['npm', 'install']
        id: 'npm-install'
        waitFor: ['-']  # step begins immediately

    # build map style
    -   name: 'node:8'
        args: ['npm', 'run', 'build:style:default']
        id: 'build-style-default'
        waitFor: ['npm-install']

# overwrite the default timeout of 10min and set it to a reasonable time window required for all above steps to complete
timeout: '1200s'
